/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package iisc.dsl.codd.client.gui;

/**
 *
 * @author Anirudh
 */
public class BaseJPanel extends javax.swing.JPanel {

    private String imagePath;
    /**
     * Creates new form BaseJPanel
     */
    public BaseJPanel(String imagePath) {
        initComponents();
        this.imagePath = imagePath;
    }
    

    @Override
    public void paintComponent(java.awt.Graphics g) {
        if(imagePath == null){
            super.paintComponent(g);
            return;
        }
        java.awt.Image img = new javax.swing.ImageIcon(imagePath).getImage();
        g.drawImage(img, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
