dict_2d = {	
	(('Q7' ,),'CHAIN')               :[	'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk',
										'ss_sold_date_sk = d_date_sk | ss_cdemo_sk = cd_demo_sk',
										'ss_sold_date_sk = d_date_sk | ss_promo_sk = p_promo_sk',
										'ss_item_sk = i_item_sk | ss_cdemo_sk = cd_demo_sk',
										'ss_item_sk = i_item_sk | ss_promo_sk = p_promo_sk',
										'ss_cdemo_sk = cd_demo_sk | ss_promo_sk = p_promo_sk',],
	(('Q15',),'CHAIN')               :[	'cs_bill_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',
										'cs_bill_customer_sk = c_customer_sk | cs_sold_date_sk = d_date_sk',],
	(('Q19',),'CHAIN')               :[	'd_date_sk = ss_sold_date_sk | ss_item_sk = i_item_sk',
										'd_date_sk = ss_sold_date_sk | ss_store_sk = s_store_sk',
										'd_date_sk = ss_sold_date_sk | ss_customer_sk = c_customer_sk',
										'ss_item_sk = i_item_sk | ss_store_sk = s_store_sk',
										'ss_item_sk = i_item_sk | ss_customer_sk = c_customer_sk',
										'ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk',
										'ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',],
	(('Q21', 'Q22',),'CHAIN')          :[	'i_item_sk = inv_item_sk | w_warehouse_sk = inv_warehouse_sk',
										'i_item_sk = inv_item_sk | d_date_sk = inv_date_sk',
										'w_warehouse_sk = inv_warehouse_sk | d_date_sk = inv_date_sk',],
	(('Q26',),'CHAIN')               :[	'cs_sold_date_sk = d_date_sk | cs_item_sk = i_item_sk',
										'cs_sold_date_sk = d_date_sk | cs_bill_cdemo_sk = cd_demo_sk',
										'cs_sold_date_sk = d_date_sk | cs_promo_sk = p_promo_sk',
										'cs_item_sk = i_item_sk | cs_bill_cdemo_sk = cd_demo_sk',
										'cs_item_sk = i_item_sk | cs_promo_sk = p_promo_sk',
										'cs_bill_cdemo_sk = cd_demo_sk | cs_promo_sk = p_promo_sk',],
	(('Q27',),'CHAIN')               :[	'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk',
										'ss_sold_date_sk = d_date_sk | ss_store_sk = s_store_sk',
										'ss_sold_date_sk = d_date_sk | ss_cdemo_sk = cd_demo_sk',
										'ss_item_sk = i_item_sk | ss_store_sk = s_store_sk',
										'ss_item_sk = i_item_sk | ss_cdemo_sk = cd_demo_sk',
										'ss_store_sk = s_store_sk | ss_cdemo_sk = cd_demo_sk',],
	(('Q37', 'Q53', 'Q67', 'Q89',),'CHAIN'):[	'd_date_sk = ss_sold_date_sk | i_item_sk = ss_item_sk',
										'd_date_sk = ss_sold_date_sk | s_store_sk = ss_store_sk',
										'i_item_sk = ss_item_sk | s_store_sk = ss_store_sk',],
	(('Q40',),'CHAIN')               :[	'i_item_sk = cs_item_sk | w_warehouse_sk = cs_warehouse_sk',
										'i_item_sk = cs_item_sk | d_date_sk = cs_sold_date_sk',
										'w_warehouse_sk = cs_warehouse_sk | d_date_sk = cs_sold_date_sk',],
	(('Q62',),'CHAIN')               :[	'd_date_sk = ws_ship_date_sk | w_warehouse_sk = ws_warehouse_sk',
										'd_date_sk = ws_ship_date_sk | sm_ship_mode_sk = ws_ship_mode_sk',
										'd_date_sk = ws_ship_date_sk | web_site_sk = ws_web_site_sk',
										'w_warehouse_sk = ws_warehouse_sk | sm_ship_mode_sk = ws_ship_mode_sk',
										'w_warehouse_sk = ws_warehouse_sk | web_site_sk = ws_web_site_sk',
										'sm_ship_mode_sk = ws_ship_mode_sk | web_site_sk = ws_web_site_sk',],
	(('Q73',),'CHAIN')               :[	'd_date_sk = ss_sold_date_sk | s_store_sk = ss_store_sk',
										'd_date_sk = ss_sold_date_sk | hd_demo_sk = ss_hdemo_sk',
										's_store_sk = ss_store_sk | hd_demo_sk = ss_hdemo_sk',],
	(('Q84',),'CHAIN')               :[	'c_current_addr_sk = ca_address_sk | cd_demo_sk = c_current_cdemo_sk',
										'cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk',
										'c_current_addr_sk = ca_address_sk | hd_demo_sk = c_current_hdemo_sk',
										'cd_demo_sk = c_current_cdemo_sk | sr_cdemo_sk = cd_demo_sk',
										'hd_demo_sk = c_current_hdemo_sk | ib_income_band_sk = hd_income_band_sk',],
	(('Q91',),'CHAIN')               :[	'cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk',
										'cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk',
										'cr_returning_customer_sk = c_customer_sk | ca_address_sk = c_current_addr_sk',
										'cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk',
										'cd_demo_sk = c_current_cdemo_sk | ca_address_sk = c_current_addr_sk',
										'hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
										'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk',
										'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk',
										'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk',],
	(('Q96',),'CHAIN')               :[	'ss_sold_time_sk = time_dim.t_time_sk | ss_hdemo_sk = hd_demo_sk',
										'ss_sold_time_sk = time_dim.t_time_sk | ss_store_sk = s_store_sk',
										'ss_hdemo_sk = hd_demo_sk | ss_store_sk = s_store_sk',],
	(('Q99',),'CHAIN')               :[	'd_date_sk = cs_ship_date_sk | w_warehouse_sk = cs_warehouse_sk',
										'd_date_sk = cs_ship_date_sk | sm_ship_mode_sk = cs_ship_mode_sk',
										'd_date_sk = cs_ship_date_sk | cc_call_center_sk = cs_call_center_sk',
										'w_warehouse_sk = cs_warehouse_sk | sm_ship_mode_sk = cs_ship_mode_sk',
										'w_warehouse_sk = cs_warehouse_sk | cc_call_center_sk = cs_call_center_sk',
										'sm_ship_mode_sk = cs_ship_mode_sk | cc_call_center_sk = cs_call_center_sk',],
}

dict_3d = {
(('Q7',),'STAR')                :[	'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk | ss_cdemo_sk = cd_demo_sk',
									'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk | ss_promo_sk = p_promo_sk',
									'ss_sold_date_sk = d_date_sk | ss_cdemo_sk = cd_demo_sk | ss_promo_sk = p_promo_sk',
									'ss_item_sk = i_item_sk | ss_cdemo_sk = cd_demo_sk | ss_promo_sk = p_promo_sk',],
(('Q15',),'CHAIN')              :[	'cs_bill_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk | cs_sold_date_sk = d_date_sk',],
(('Q19',),'CHAIN')              :[	'd_date_sk = ss_sold_date_sk | ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',
									'ss_item_sk = i_item_sk | ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',
									'ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',],
(('Q19',),'STAR')               :[	'd_date_sk = ss_sold_date_sk | ss_item_sk = i_item_sk | ss_store_sk = s_store_sk',
									'd_date_sk = ss_sold_date_sk | ss_item_sk = i_item_sk | ss_customer_sk = c_customer_sk',
									'd_date_sk = ss_sold_date_sk | ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk',
									'ss_item_sk = i_item_sk | ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk',],
(('Q21', 'Q22',),'STAR')          :[	'i_item_sk = inv_item_sk | w_warehouse_sk = inv_warehouse_sk | d_date_sk = inv_date_sk',],
(('Q26',),'STAR')               :[	'cs_sold_date_sk = d_date_sk | cs_item_sk = i_item_sk | cs_bill_cdemo_sk = cd_demo_sk',
									'cs_sold_date_sk = d_date_sk | cs_item_sk = i_item_sk | cs_promo_sk = p_promo_sk',
									'cs_sold_date_sk = d_date_sk | cs_bill_cdemo_sk = cd_demo_sk | cs_promo_sk = p_promo_sk',
									'cs_item_sk = i_item_sk | cs_bill_cdemo_sk = cd_demo_sk | cs_promo_sk = p_promo_sk',],
(('Q27',),'STAR')               :[	'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk | ss_store_sk = s_store_sk',
									'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk | ss_cdemo_sk = cd_demo_sk',
									'ss_sold_date_sk = d_date_sk | ss_store_sk = s_store_sk | ss_cdemo_sk = cd_demo_sk',
									'ss_item_sk = i_item_sk | ss_store_sk = s_store_sk | ss_cdemo_sk = cd_demo_sk',],
(('Q37', 'Q53', 'Q67', 'Q89',),'STAR'):[	'i_item_sk = ss_item_sk | d_date_sk = ss_sold_date_sk | s_store_sk = ss_store_sk',],
(('Q40',),'STAR')               :[	'i_item_sk = cs_item_sk | w_warehouse_sk = cs_warehouse_sk | d_date_sk = cs_sold_date_sk',],
(('Q62',),'STAR')               :[	'd_date_sk = ws_ship_date_sk | w_warehouse_sk = ws_warehouse_sk | sm_ship_mode_sk = ws_ship_mode_sk',
									'd_date_sk = ws_ship_date_sk | w_warehouse_sk = ws_warehouse_sk | web_site_sk = ws_web_site_sk',
									'd_date_sk = ws_ship_date_sk | sm_ship_mode_sk = ws_ship_mode_sk | web_site_sk = ws_web_site_sk',
									'w_warehouse_sk = ws_warehouse_sk | sm_ship_mode_sk = ws_ship_mode_sk | web_site_sk = ws_web_site_sk',],
(('Q73',),'STAR')               :[	'd_date_sk = ss_sold_date_sk | s_store_sk = ss_store_sk | hd_demo_sk = ss_hdemo_sk',],
(('Q84',),'CHAIN')              :[	'c_current_addr_sk = ca_address_sk | cd_demo_sk = c_current_cdemo_sk | sr_cdemo_sk = cd_demo_sk',
									'c_current_addr_sk = ca_address_sk | hd_demo_sk = c_current_hdemo_sk | ib_income_band_sk = hd_income_band_sk',
									'cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | sr_cdemo_sk = cd_demo_sk',
									'cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ib_income_band_sk = hd_income_band_sk',],
(('Q84',),'STAR')               :[	'c_current_addr_sk = ca_address_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk',],
(('Q91',),'CHAIN')              :[	'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk | ca_address_sk = c_current_addr_sk',
									'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk',
									'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk',
									'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | ca_address_sk = c_current_addr_sk',],
(('Q91',),'STAR')               :[	'cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk',
									'cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
									'cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk',],
(('Q96',),'STAR')               :[	'ss_sold_time_sk = time_dim.t_time_sk | ss_hdemo_sk = hd_demo_sk | ss_store_sk = s_store_sk',],
(('Q99',),'STAR')               :[	'd_date_sk = cs_ship_date_sk | w_warehouse_sk = cs_warehouse_sk | sm_ship_mode_sk = cs_ship_mode_sk',
									'd_date_sk = cs_ship_date_sk | w_warehouse_sk = cs_warehouse_sk | cc_call_center_sk = cs_call_center_sk',
									'd_date_sk = cs_ship_date_sk | sm_ship_mode_sk = cs_ship_mode_sk | cc_call_center_sk = cs_call_center_sk',
									'w_warehouse_sk = cs_warehouse_sk | sm_ship_mode_sk = cs_ship_mode_sk | cc_call_center_sk = cs_call_center_sk',],
}

dict_4d = {
(('Q7',),'STAR')                :[	'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk | ss_cdemo_sk = cd_demo_sk | ss_promo_sk = p_promo_sk',],
(('Q19',),'HYBRID')             :[	'd_date_sk = ss_sold_date_sk | ss_item_sk = i_item_sk | ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',
									'd_date_sk = ss_sold_date_sk | ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',
									'ss_item_sk = i_item_sk | ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',],
(('Q19',),'STAR')               :[	'd_date_sk = ss_sold_date_sk | ss_item_sk = i_item_sk | ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk',],
(('Q26',),'STAR')               :[	'cs_sold_date_sk = d_date_sk | cs_item_sk = i_item_sk | cs_bill_cdemo_sk = cd_demo_sk | cs_promo_sk = p_promo_sk',],
(('Q27',),'STAR')               :[	'ss_sold_date_sk = d_date_sk | ss_item_sk = i_item_sk | ss_store_sk = s_store_sk | ss_cdemo_sk = cd_demo_sk',],
(('Q62',),'STAR')               :[	'd_date_sk = ws_ship_date_sk | w_warehouse_sk = ws_warehouse_sk | sm_ship_mode_sk = ws_ship_mode_sk | web_site_sk = ws_web_site_sk',],
(('Q84',),'CHAIN')              :[	'cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ib_income_band_sk = hd_income_band_sk | sr_cdemo_sk = cd_demo_sk',],
(('Q84',),'HYBRID')             :[	'c_current_addr_sk = ca_address_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ib_income_band_sk = hd_income_band_sk',
									'c_current_addr_sk = ca_address_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | sr_cdemo_sk = cd_demo_sk',],
(('Q91',),'HYBRID')              :[	'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk',
									'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk',],
(('Q91',),'STAR')               :[	'cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',],
(('Q99',),'STAR')               :[	'd_date_sk = cs_ship_date_sk | w_warehouse_sk = cs_warehouse_sk | sm_ship_mode_sk = cs_ship_mode_sk | cc_call_center_sk = cs_call_center_sk',],
}

dict_5d = {
(('Q19',),'HYBRID')             :[	'd_date_sk = ss_sold_date_sk | ss_item_sk = i_item_sk | ss_store_sk = s_store_sk | ss_customer_sk = c_customer_sk | c_current_addr_sk = ca_address_sk',],
(('Q84',),'HYBRID')             :[	'c_current_addr_sk = ca_address_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ib_income_band_sk = hd_income_band_sk | sr_cdemo_sk = cd_demo_sk',],
(('Q91',),'HYBRID')             :[	'cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | hd_demo_sk = c_current_hdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | ca_address_sk = c_current_addr_sk',
									'cr_call_center_sk = cc_call_center_sk | cr_returned_date_sk = d_date_sk | cr_returning_customer_sk = c_customer_sk | cd_demo_sk = c_current_cdemo_sk | hd_demo_sk = c_current_hdemo_sk',],
}


pred_dct = {2:dict_2d, 3:dict_3d, 4:dict_4d, 5:dict_5d }